### ISSUE TITLE
Class loading from ServletContext

### ISSUE THREAD

**Issue by Tires** [ocpsoft/rewrite#228]
External class paths should be respected in Tomcat, but are not. The problem is in /rewrite-annotations-impl/src/main/java/org/ocpsoft/rewrite/annotation/scan/WebClassesFinder.java:79:

classFileStream = entryUrl.openStream();

but, in my opinion, should be:

classFileStream = servletContext.getResourceAsStream(entryName);

Additionally, the method parameter URL entryUrl could be removed both from handleClassEntry and processDirectory including constructional code.

**Comment by chkal** [comment]
Could you explain what you mean with "external class paths"?

I wrote this class path scanning quite some time ago. And to be honest I would like to drop it in the next major release and replace it with something like the Reflections library. Especially because the current code also doesn't work well with Spring Boot.

**Comment by Tires** [comment]
I'm working with Spring Boot also. External class paths mean, that an application server can map virtual paths to eg.

<Context>
    <Resources className="org.apache.catalina.webresources.StandardRoot">
        <PreResources className="org.apache.catalina.webresources.DirResourceSet"
            base="C:\\some\\path"
            internalPath="/"
            webAppMount="/WEB-INF/classes" />
    </Resources>
</Context>

or by extending org.apache.catalina.loader.WebappLoader

The result in either case is, that the relative path result from servletContext.getResourcePaths cannot necessarily be directly translated to absolute paths in the file system. But

servletContext.getResourceAsStream(entryName);

respects that web app mounts. Concrete spoken, I'm using com.intersult:maven-loader with Tomcat 8.

**Comment by chkal** [comment]
Thanks for sharing these details. 

As I wrote before I'm aware that the current scanning codes doesn't work in some scenarios like Spring Boot. But to be honest, I'm a bit conservative in changing the code, because it is very difficult to test all possible deployment scenarios. That's why I'm thinking about replacing all my hand-written code with some real annotation scanning library.

Did you test the modification you are suggesting and does it work with Spring Boot then?

**Comment by Tires** [comment]
I understand that this is a sensitive point and one can never be sure about the consequences of code changes. The method getResourceAsStream is a very old method from ServletContext, which is also suggested to be used on Google App Engine.

This would be more a quick fix, because class path detection is better done by finding META-INF/MANIFEST.MF, which a classpath scanner essentially does. But will going to get a larger code change.

Yes, I'm currently running on Spring Boot 1.3.3, JSF 2.2.12, Primefaces 5.3 and Rewrite 3.0.0-SNAPSHOT in (a) starting from Eclipse Workspace, which has just another class loading, (b) from maven tomcat7:run, (c) deploying on Tomcat 8.0.32 as exploded and (d) deploying on Tomcat 8.0.32 as war. Each with and without as called Thin WARs, where the application server adds class path elements from an embedded pom.xml.

**Comment by chkal** [comment]
Ok thanks. Looks like you tested a large number of class loading scenarios. And all of this worked fine with your patch applied? That would be awesome. In this case I'm +1 for applying the patch. Just see my open question in the PR.

**Comment by Tires** [comment]
The old scenarios continue to work and the new scenarios now do work, too. The reason for me to make this changes, was to get the new scenarios work.

What open question you're talking about?

**Comment by chkal** [comment]
Ok, great. 

The question about your change of `IOException` to `Exception`. I posted this to the PR.

**Comment by chkal** [comment]
Fixed with #230
