### ISSUE TITLE
No Parameters set when using @Inject HttpServletRequest

### ISSUE THREAD

**Issue by b0rengar** [ocpsoft/rewrite#235]
Hello,

I try to access url parameters in my bean using a injected HttpServletRequest object but getParameter-Method always returns null. If I use FacesContext to get the request object everything works as expected.

Untested minimal example:

```java
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;

@Named
public class MyBean {

    @Inject
    protected HttpServletRequest injectedRequest;

    public void myMethod() {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();

        System.out.println(injectedRequest.getParameter("param"));//returns null
        System.out.println(request.getParameter("param"));//returns expected value
    }
}
```
I'm using Wildfy 10 and have rewrite-servlet and rewrite-integration-cdi with version 2.0.12.Final in my Maven dependencies.

**Comment by chkal** [comment]
I guess this is caused by the fact that Rewrite uses a servlet filter which wraps the `HttpServletRequest` and passes this wrapped request further down the filter chain. The servlet processing the request (the FacesServlet in this case) gets this wrapped request and is therefore able to access the request parameters added by Rewrite. Unfortunately CDI injection doesn't honor this wrapping mechanism. So you will get the unwrapped request which doesn't contain these parameters.

Not sure if the CDI spec requires it to work this way or if it simply isn't explicitly defined.

A workaround would be to define a custom producer with a special qualifier that uses the FacesContext to obtain the request:

```java
@Produces
@RequestScoped
@MyCustomQualifier
public HttpServletRequest getWrappedRequest() {
  FacesContext context = FacesContext.getCurrentInstance();
  return (HttpServletRequest) context.getExternalContext().getRequest();
}
```

And then use this way to inject the request:

```java
@Inject
@MyCustomQualifier
private HttpServletRequest request;
```

**Comment by b0rengar** [comment]
Thank you for your response. It would be great if you could integrate this into your Documentation.
