### ISSUE TITLE
Case Insensitive Path?

### ISSUE THREAD

**Issue by melloware** [ocpsoft/rewrite#247]
I have a simple request.  I am trying the following:
`
.addRule().when(Direction.isInbound().and(Path.matches("/TEST/INFO.HTM"))).perform(Forward.to("/pages/info.xhtml"));`

I want it to work if I type in any case insensitve version of the URL like...
/test/info.htm
/TEST/info.htm
/TEST/INFO.htm
/test/INFO.HTM
etc...

I tried doing Path.matches("(?i)/TEST/INFO.HTM") using ?i but that has had no effect.  My question is how do i accomplish what I want to do?

**Comment by lincolnthree** [comment]
My recommendation would be to first do an internal forward or redirect in which you lowercase the path. Supporting case-insensitive paths is a bit of an anti-pattern due to the fact that it creates multiple URLs for the same resource.

That said, you can effectively achieve this, and you probably want to use a global rule before your individual routing rules:

Implement a Lowercase Transposition:

```
Transposition<String> lowercase = new Transposition<String>() {

         @Override
         public String transpose(Rewrite event, EvaluationContext context, String value)
         {
            return value.toLowerCase();
         }
      };
```
Then use this in a rule where you match only on requests that have uppercase characters (You don't want to redirect requests that have lowercase characters, or that are literal filenames, or handled by other servlets, in theory... this might take a little tweaking to get right.
```
.addRule()
.when(
   Direction.isInbound()
      .and(Path.matches("/{p}"))
      .andNot(Resource.exists("/{p}")
)
.perform(Redirect.permanent(context.getContextPath() + "/{p}"))
.where("p").matches("(?=[A-Z]).*").transposedBy(lowercase)
```

Note, I have not tested this code, it is just pseudocode/an example off the top of my head. I hope this helps.

**Comment by lincolnthree** [comment]
Actually, it might be better to do this with a `Converter`, not a `Transposition`, since that happens after the matching stage. But try both and see which one meets your needs.

**Comment by melloware** [comment]
Thanks for this.  I will give this a shot and report back.   I definitely know its an anti-pattern however my client has some specific requirements of URL's like the ones I mentioned above so I wanted a way of generically handling it.  I think a global rule like you suggest above is what I am looking for.
