### ISSUE TITLE
Removing the context root in the path of a jsf app

### ISSUE THREAD

**Issue by seinecle** [ocpsoft/rewrite#300]
Hi,
Just in case, could anyone check if this question I posted on stackoverflow could be solved with rewrite?
https://stackoverflow.com/questions/67559670/remove-subpath-context-root-in-nginx-for-a-java-app

Thank you!

**Comment by lincolnthree** [comment]
Hey there @seinecle  - As you already know - StackOverflow is probably the best place to ask this question, I appreciate you looking into whether rewrite can do this for you, though.

Since Rewrite operates within a Servlet Context, it cannot change the servlet context root path. This has to be done either at the web-application server or web HTTP proxy levels. Rewrite can, however, change anything within a servlet context root, or redirect/proxy to a different context root.
